### ISSUE TITLE
Bug to modal

### ISSUE THREAD

**Issue by musicman3** [mymth/vanillajs-datepicker#50]
There is a bug when placed in a modal window. 
![Снимок экрана 2021-02-16 171952](https://user-images.githubusercontent.com/36889207/108082922-39ec2e00-707b-11eb-9b98-bd030321e7de.png)

**Comment by mymth** [comment]
Setting `.modal` to the `container` option should solve it.
```javascript
const datepicker = new Datepicker(elem, {
  container: '.modal',
});
```

This date picker doesn't control picker's z-index programmatically, but only in CSS. I think this approach is better because the range of z-indices varies from framework to framework. The default z-index is set to the same as the one of each framework's dropdown. This was chosen because I thought date picker's behaviour is the closest to dropdowns and modals are more commonly used for alert/confirmation than popup form.

Now, if you set `container: '.modal'`, the picker element is appended to `.modal`'s children instead of the default container, `<body>`'s. Since `.modal` element has `position: fixed`, it changes the picker's stacking context to `.modal`'s and the  z-index of the picker is evaluated within the modal's element tree. As a result, the picker is displayed above the modal's backdrop.

You can also override the picker's z-index in your stylesheet.

```scss
// with sass variable
$dp-dropdown-z: 9999; // arbitrary number higher than .modal's z-index

// Or with css
.datepicker-dropdown {
  z-index: 9999; // arbitrary number higher than .modal's
}
```
